### ISSUE TITLE
ValueError: call auth error, message: Failed to find valid AK

### ISSUE THREAD

**Issue by SiyuYan02** [UniModal4Reasoning/SimChart9K#1]
meet ValueError: call auth error, message: Failed to find valid AK after  openxlab login

**Comment by BOBrown** [comment]
@SiyuYan02 右侧账户图标 -> 账号与安全 ->  左侧的密钥管理 -> 添加密钥

Account Security on the Account icon (upper right corner) -> AK/SK -> Create Key

**Comment by BOBrown** [comment]
@SiyuYan02 

This issue will be closed due to prolonged inactivity. If further discussion is needed, please reopen this issue.
