### ISSUE TITLE
403: {"code":403,"msg":{"en":"To better provide you with data services, please go to the PC version of this dataset detail page and click \"Download\" to fill out the user information collection form.","zh":"To better provide you with data services, please go to the PC version of this dataset detail page and click \"Download\" to fill out the user information collection form."}}

### ISSUE THREAD

**Issue by dydxdt** [UniModal4Reasoning/SimChart9K#2]
Great work! How to download the dataset?
When I run "openxlab dataset get --dataset-repo  Lonepic/SimChart9K", it shows:
0%|                                                                          | 0/3 [00:00<?, ?it/s] Downloading No.1 of total 3 files
403: {"code":403,"msg":{"en":"To better provide you with data services, please go to the PC version of this dataset detail page and click \"Download\" to fill out the user information collection form.","zh":"To better provide you with data services, please go to the PC version of this dataset detail page and click \"Download\" to fill out the user information collection form."}}
  0%|                                                                          | 0/3 [00:00<?, ?it/s]

**Comment by BOBrown** [comment]
@dydxdt 
Hi, have you added the AK/SK when downloading the dataset?
