### ISSUE TITLE
Question about the training

### ISSUE THREAD

**Issue by yefangok** [UniModal4Reasoning/SimChart9K#4]
![截图 2024-01-19 11-44-10](https://github.com/UniModal4Reasoning/SimChart9K/assets/465437/a38be254-e371-435a-8ea6-921f0594501c)
According to the screenshot in the paper, LCT data is used in the training phase and converted to STR in the evaluation phase. Why not train STR data directly?

**Comment by renqiux0302** [comment]
Yes, we use LCT data in training phase and convert to STR for evaluation. Since the token length of STR is longer than LCT, training with STR will occupy more GPU memory. Thanks for your suggestion, we will try to conduct training with STR data in our next version.
