### ISSUE TITLE
command not found: openxlab

### ISSUE THREAD

**Issue by whitesockcat** [UniModal4Reasoning/SimChart9K#5]
pip3 install openxlab success.
but openxlab login fail

**Comment by BOBrown** [comment]
Hi, we add the [download link](https://drive.google.com/file/d/1M_NA3sIJNwCUfqB1HH0p4lsnEm3NbvsI/view) from Google Drive. @whitesockcat

**Comment by whitesockcat** [comment]
THANK YOU 😄
