### ISSUE TITLE
code of SCRM

### ISSUE THREAD

**Issue by YaoyaoChang** [UniModal4Reasoning/SimChart9K#7]
As paper mentioned, SCRM(Structuring Chartoriented Representation Metric) is proposed to better evaluate chart-to-table task.
Where is the code of SCRM? Will you open source it in the future?

**Comment by BOBrown** [comment]
@YaoyaoChang Hi, you can find the SCRM code in [ChartX repo](https://github.com/UniModal4Reasoning/ChartVLM/blob/main/eval/metric/SCRM.py). For ChartX dataset, we also use the SCRM to evaluate the task of chart domain-related structuring extracting.

**Comment by YaoyaoChang** [comment]
Great work. Got it. Thanks!
